{
  "formatVersion": "1.1",
  "component": {
    "group": "aimerwjy.asm.plugin",
    "module": "android_monitor_asm_plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "android_monitor_asm_plugin-1.0.0.jar",
          "url": "android_monitor_asm_plugin-1.0.0.jar",
          "size": 12799,
          "sha512": "40d1bf2bbd7391dcf4ef819b085dd666f64ea4ee0ad7a66ce3161141dabd87b941ff2de7e5b427ffdbf0e8ed8076e4fe5cae3b5e005ac0069af87067f68aa767",
          "sha256": "75f591c99a93f195f73d91553b62a720f4e5c4d324ead3209a111b80853baf4c",
          "sha1": "c82c0e5112c7c9fab8fae2943c1eb13b11a1f912",
          "md5": "127cd587495c64795c37389cbb1ac246"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "3.5.4"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.1"
          }
        }
      ],
      "files": [
        {
          "name": "android_monitor_asm_plugin-1.0.0.jar",
          "url": "android_monitor_asm_plugin-1.0.0.jar",
          "size": 12799,
          "sha512": "40d1bf2bbd7391dcf4ef819b085dd666f64ea4ee0ad7a66ce3161141dabd87b941ff2de7e5b427ffdbf0e8ed8076e4fe5cae3b5e005ac0069af87067f68aa767",
          "sha256": "75f591c99a93f195f73d91553b62a720f4e5c4d324ead3209a111b80853baf4c",
          "sha1": "c82c0e5112c7c9fab8fae2943c1eb13b11a1f912",
          "md5": "127cd587495c64795c37389cbb1ac246"
        }
      ]
    }
  ]
}
